# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionpointapp', '0006_auto_20190308_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('numOfLikes', models.PositiveIntegerField(default=0)),
                ('numOfDislikes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('numOfLikes', models.PositiveIntegerField(default=0)),
                ('numOfDislikes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='avgRating',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='rating',
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='picture1',
            field=models.ImageField(upload_to='polls/'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='picture1Clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='picture2',
            field=models.ImageField(upload_to='polls/'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='picture2Clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionpointapp.Poll'),
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionpointapp.Post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionpointapp.Post'),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionpointapp.Poll'),
        ),
    ]
