# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionpointapp', '0008_auto_20190308_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcomment',
            name='numOfDislikes',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='numOfLikes',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='numOfDislikes',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='numOfLikes',
        ),
    ]
