# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionpointapp', '0014_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='rating',
            new_name='type',
        ),
    ]
