# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionpointapp', '0017_merge_20190322_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionpointapp.PollComment')),
                ('userPofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionpointapp.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'likesP',
            },
        ),
    ]
