# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionpointapp', '0019_auto_20190322_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fashionista',
            field=models.BooleanField(default=False),
        ),
    ]
