# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionpointapp', '0020_userprofile_fashionista'),
        ('fashionpointapp', '0017_merge_20190322_0333'),
    ]

    operations = [
    ]
